
name: Clone Private Repository Workflow

on:
  workflow_dispatch:

jobs:
    
  job-public-repo-ubuntu:
    runs-on: ubuntu-latest
    steps:
      
      - name: Clone fonestardev/fonestar-unity PRIVATE repository
        uses: fonestardev/checkout@master
        with:
          owner: 'fonestardev'
          branch: master
          repository: 'audio-testing'
          access-token: ${{ secrets.ACCESS_TOKEN }}
      
      - name: Access cloned repository content
        run: |
          echo "ROOT"
          ls -la
          echo "CLONED REPO"
          cd audio-testing
          ls -la